### ISSUE TITLE
Nested pulls don't get correct datatype

### ISSUE THREAD

**Issue by mgerlach-klick** [coast-framework/coast#34]
If I have a `:user/date` and a `:company/date` and both are of type `timestamptz`and there are many users in a company, and I do a `(q '[:pull [:company/date {:company/users [:user/date]}]])` then `:company/date` will be an instant, but `:user/date` a string.

I don't quite understand how you're doing the pull magic, but it seems like there's a final tree traversal that converts datatypes, or something like that, missing

**Comment by swlkr** [comment]
Yeah it's interesting, I thought the extension to read json from postgres would handle this, but unfortunately, it does not. 

Another option which I was kind of not wanting to do because I sort of already hacked up a solution using this is `clojure.walk` where I look for postgres date/time columns in `schema.edn` and parse dates to instants, manually.

Maybe I can figure out a way to extend the postgres driver to do this though.

**Comment by mgerlach-klick** [comment]
I stared at your code in https://github.com/coast-framework/coast/blob/master/src/coast/db/query.clj for a while and now have a general idea on how you do things (related, it would be super helpful if you put some docstrings on the namespaces that explain the general ideas of what's happening). 

So yeah, if you're building a JSON object, you will always just get text. Postgres has no idea what text represents a date or a datetime, and converting them just by pattern-matching could lead to some awkward false-positives. I can't think of a way that doesn't involve a tree-walk either..
