### ISSUE TITLE
why not to use Toucan?

### ISSUE THREAD

**Issue by mrkaspa** [coast-framework/coast#58]
Toucan https://github.com/metabase/toucan is a great and battle tested ormish library and used a lot in metabase, it will be good to integrate this with coast

**Comment by swlkr** [comment]
There's nothing stopping you from using toucan with coast right now:

```clojure
(ns server
  (:require [toucan.db :as db]
                 [coast]))

; … app stuff here

(defn -main [& args]
  ; … server call here
  (db/set-default-db-connection! (coast/connection))
```

I haven't really used toucan before, but this should work since `connection` returns coast's connection pool which gets passed to `clojure.java.jdbc` anyway.

I should probably take a minute to mention why I didn't use any of the existing clojure database libraries like honeysql, toucan, yesql, hugsql, korma, SQLingvo, oj, suricatta, or aggregate.

I can sum it up with one word: integration.

The reality is a little more messy though. I'm really aiming to have coast be as cohesive *and* as easy as rails, that means "conventions", i.e. hardcoding what would be glue code between the various clojure libraries that you would have to write yourself. So in the case of toucan, it expects you to lay out your database schema in a certain way for hydration to work, append references with `table_name` + `_id`. So if you used ragtime for migrations, you would have to manually write SQL migrations appending `_id` to all of your fk columns. It's a small thing that you would think doesn't matter, but the reason rails is such a smooth experience is that the whole is greater than the sum of the parts. All of the little things add up and you eventually get to a higher level of abstraction which allows you to move much faster when developing web applications.

In coast, since [migrations](https://github.com/coast-framework/coast/blob/master/docs/migrations.md) and [associations](https://github.com/coast-framework/coast/blob/master/docs/relationships.md) are kept in mind as two things that go together, like peanut butter and jelly (or chocolate, if that's your thing), you don't have to think about this minutia anymore, and it frees you to focus on app specific things by just writing a coast-y migration: `(references :table-name)`.

Rails also did the dirty work of auto-requiring things so you don't have to `:require` every little thing, which is something that I'm still working on with coast. This is also one of those "does this small thing really matter?" things but it winds up being a boon to productivity. So I also didn't use toucan because as coast is now I would have to require the model namespace, or require refer each model (similar to the way components is now, which I hate) and I'm not exactly sure how to auto-require things in clojure just yet without turning every function call into a runtime `:resolve` situation with each function being a keyword instead of a symbol.

So, it was long winded, but I don't use certain libraries because I want complete control over the coast experience and since existing clojure libraries care more about simplicity vs ease, which is a very noble goal, I wind up not using them more often than I use them.

I'm not opposed to using toucan, but I also think [pull](https://github.com/coast-framework/coast/blob/master/docs/pull.md) is pretty sweet in terms of hydration 😉
