### ISSUE TITLE
localhost:1337/todos ui not responsive

### ISSUE THREAD

**Issue by elamje** [coast-framework/coast#69]
When clicking `new todo` on the screen, nothing happens although the server gets hit with a GET "/todos/build" 200. Form on next page does not do anything or even hit the server

**Comment by swlkr** [comment]
I was really excited to get rid of jquery [here](https://github.com/coast-framework/template/commit/f5c0d1c9a524713133eeb22b6b9c5f53932b2f2b), but in my haste, I called `e.preventDefault()` on all anchor tags 😅

[The fix is in](https://github.com/coast-framework/template/commit/ad30b48317f9765a0ddc713dcdf6f2529a246d12)

**Comment by elamje** [comment]
Wonderful! It works!
